#!/bin/sh
#Start the server
if [ $1 ] && [ $1 = "arm" ]
then
  echo "Starting for ARM systems"
  IMAGE='hareemca123/pure-ftpd'
else
  echo "Starting for x86 systems"
  IMAGE='stilliard/pure-ftpd:hardened'
fi

echo Starting FTP server...
CALL="docker run -d --rm \
	--name deezloader_ftpd_server \
	-p 21:21 -p 30000-30009:30000-30009 \
	-v deezloader:/app:rw \
	-v deezloader-ftp-passwd:/etc/pure-ftpd/passwd:rw \
	-v deezloader-ftp-users:/home/ftpusers:rw \
	-e \"PUBLICHOST=localhost\" $IMAGE"
$CALL

echo Starting the deezloader server...
docker run --rm -d\
	-p 1720:1720 \
	-v deezloader:/app \
	--name "deezloader"\
	deezloader:latest

NEW_USER="docker exec -it deezloader_ftpd_server /usr/bin/pure-pw useradd $username -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /app/node_modules/deezloader-server/mp3"
if [ $1 ] && [ $1 = "arm" ]
then
   echo "This is a workaround for ARM based systems"
   $NEW_USER
fi

echo Startup complete. Save music with localhost:1720. Transfer music with \'ftp localhost 21\' 
