#!/bin/sh
#Start the server
if [ $1 ] && [ $1 = "arm" ]
then
  echo "Starting for ARM systems"
  IMAGE='hareemca123/pure-ftpd'
else
  echo "Starting for x86 systems"
  IMAGE='stilliard/pure-ftpd:hardened'
fi

echo Starting FTP server...
CALL="docker run -d --rm \
	--name deezloader_ftpd_server \
	-p 21:21 -p 30000-30009:30000-30009 \
	-v deezloader:/app \
	-v deezloader-ftp-passwd:/etc/pure-ftpd/passwd \
	-v deezloader-ftp-users:/home/ftpusers
	-e \"PUBLICHOST=localhost\" $IMAGE"
$CALL

echo Starting the deezloader server...
docker run --rm -d\
	-p 1720:1720 \
	-v deezloader:/app \
	--name "deezloader"\
	deezloader:latest


echo Startup complete. Save music with localhost:1720. Transfer music with \'ftp localhost 21\' 
